
service: serverless-sqs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: staging
  region: eu-central-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - !GetAtt DemoQueue.Arn

plugins:
  - serverless-esbuild

package:
  patterns:
    - config.yml
    
resources:
  Resources:
    DemoQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: DemoQueue
        DelaySeconds: 0
        MessageRetentionPeriod: 345600
        VisibilityTimeout: 30
        RedrivePolicy: 
          deadLetterTargetArn: 
            Fn::GetAtt: 
              - "DeadLetterQueue"
              - "Arn"
          maxReceiveCount: 2
    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: dlq
  Outputs:
    sqsArn:
      Value: !GetAtt DemoQueue.Arn
    sqsUrl:
      Value: !GetAtt DemoQueue.QueueUrl

functions:
  sendMessage:
    handler: handler.sendMessage
  receiveMessage:
    handler: handler.receiveMessage
    events:
      - sqs:
          arn: !GetAtt DemoQueue.Arn
          batchSize: 5
          functionResponseType: ReportBatchItemFailures
